workflow_tag_fix (#33)
Reviewed-on: https://git.kundeng.us/phoenix/icarus_models/pulls/33
Co-authored-by: phoenix <kundeng94@gmail.com>
Co-committed-by: phoenix <kundeng94@gmail.com>

diff --git a/.gitea/workflows/tag_release.yaml b/.gitea/workflows/tag_release.yaml
--- a/.gitea/workflows/tag_release.yaml
+++ b/.gitea/workflows/tag_release.yaml
@@ -42,6 +42,12 @@ jobs:
           echo "Printing version"
           echo "Version: ${{ steps.version.outputs.project_tag_release }}"
 
+      - name: Check Branch
+        if: github.ref != 'refs/heads/main' || github.ref != 'refs/heads/devel' # Replace 'main' with your required branch
+        run: |
+          echo "::error::Release can only be created from the 'main' branch."
+          exit 1
+
       - name: Create GitHub Release
         uses: actions/create-release@v1
         env:
